baseURL = "https://kevinapple.github.io/"
languageCode = "en-us"
title = "Archer Zou"
theme = "timer-hugo"
publishDir = "kevinapple.github.io"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "Service"
        url     = "service"
        weight  = 3
    [[menu.nav]]
        name    = "Gallery"
        url     = "gallery"
        weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "blog"
        weight  = 5
    [[menu.nav]]
        name    = "Contact"
        url     = "contact"
        weight  = 6

# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "Airspace Hugo theme"
    author = "Archer Zou"
    # Google Analitycs
    googleAnalitycsID = "Your ID"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "HI, MY NAME IS ARCHER ZOU & I AM A"
        description = "I HAVE BEEN WORKING AS A SENIOR SOFTWARE DEVELOPER IN SUZHOU FOR MANY YEARS,  AND I AM OPEN FOR ANY OPPORTUNITIES IN THIS FIELD OR SOFTWARE ENGINEERING, SO CONTACT WITH ME."
        image  = true
        imageSrc  = "images/kevin.jpg"
        [[params.banner.flipText]]
            title   = "DESIGNER"
        [[params.banner.flipText]]
            title   = "DEVELOPER"
        [[params.banner.flipText]]
            title   = "ENGINEER"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT ME"
        content = "I am a self-employed software and web engineer dedicated to learning and teaching JavaScript for client-server architectures. I try my best to have a positive impact on the people around me. Even though I do a lot of programming in my professional and spare time, there are other things I treasure too.  I’m always struggling to memorize my learnings. I hope that I can write down my notes of books I enjoyed to read. I am happy to welcome you on my website. "
        image   = "images/about/robot.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "SO WHAT YOU THINK ?"
        content = "Now you know a bit more about me 😊 You know how you could support me and how to work with me. "
        btnText = "Contact with me"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Latest Works"
        subtitle= "I spend a lot of my free time on learning. Several hours a working week and most of my weekend time. Along the way, I have built a massive e-commerce application similar to Shopify using React, Redux, React Hooks, React Router, GraphQL, Context API, Firebase, Redux-Saga, Stripe + more. This is going to be a full stack app (MERN stack), using Firebase."

    [params.footer]
        [[params.footer.socialIcon]]
            icon = "ion-social-facebook"
            url = "#"

        [[params.footer.socialIcon]]
            icon = "ion-social-instagram"
            url = "#"

        [[params.footer.socialIcon]]
            icon = "ion-social-linkedin"
            url = "#"
